global.Ractive = require( 'ractive' )
global.Ractive.components.autocomplete = require( 'ractive-autocomplete' )
global.constants = require( './constants.json' )
global.makeNewProxy = require( 'proxify-objects' )
global.utils = require( './utils' )
